repos:
-   repo: https://github.com/ambv/black
    rev: 21.5b1
    hooks:
    - id: black
      # language_version: python3.7
      stages: [commit]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      stages: [commit]
      
-   repo: local
    hooks:
    - id: django-test
      name: django-test
      language: system
      entry: python manage.py test
      pass_filenames: false
      always_run: true
      stages: [commit]
