language: python

python:
 - 3.7.9

install:
- pip install pipenv
- pipenv install --dev

script:
- python manage.py test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
