# Vim Rest Test
# <C-j> to run test
#

http://192.168.33.20:8000
GET /account/v1/status

http://192.168.33.20:8000
POST /account/v1/login/
{
    "username": "jarteaga",
    "email": "",
    "password": "Developer"
}

http://192.168.33.20:8000
Authorization: Token 3469a795c9fbe0ded72a0fdaba6b06ec9860855e
Cookie: csrftoken=MHECIg6gioFvl0OGsdaGPjVHuXfdDBXXw3LbM5HdPhmMnD4EBPdlhoKx62o2V5NR; sessionid=4h8s8xhjnme1rjr5r0l5h2k41wjzj9av
GET /account/v1/user/

http://192.168.33.20:8000
Authorization: Token 3469a795c9fbe0ded72a0fdaba6b06ec9860855e
GET /account/v1/status
